services:
  jarvis:
    build:
      context: ./jarvis
      target: dev
    ports:
      - '8080:8080'
    env_file:
      - ./jarvis/.env
    environment:
      - LOG_LEVEL=debug
    volumes:
      - ./jarvis:/app
      - jarvis_node_modules:/app/node_modules
    restart: unless-stopped

volumes:
  jarvis_node_modules:
